### ISSUE TITLE
[Bug]: n_predict error and chat don't work. App: 1.6.0

### ISSUE THREAD

**Issue by bi4key** [a-ghorbani/pocketpal-ai#136]
**Describe the bug**
Change n_predict value and chat don't work and I see error. 
Now nothing work even when I set value to any number.

**To Reproduce**
1. Go to Models
2. Click on Settings
3. Change value n_predict to 5000 (miss click, value I wanted was 500)
4. See error "value must be between 1 to 4096"
5. Write good value 500
6. Load model
7. Say something on chat
8. See error "Completion failed: Value n_predict cannot be cast from String to double"

**Expected behavior**
Simple change value n_predict without error

**Screenshots**

Error on chat:

![Screenshot_20241211-222410_1](https://github.com/user-attachments/assets/43796984-7c1c-4147-9cd3-591eda1277fd)

Change value:

![Screenshot_20241211-223859_1](https://github.com/user-attachments/assets/481e5876-67c1-484a-9263-91bd70987c4d)

Model:

![Screenshot_20241211-223712_1](https://github.com/user-attachments/assets/700f1801-5ca7-4156-9b01-7ee5ec8862d1)

**Environment:**
- Device: [Pixel 6a ]
- OS: [ (GrapheneOS) | Android 15 ]
- App Version: [ 1.6.0 (39) ] - app from Github

**Additional context**
When I add this model, and use Default value, nothing change, then everything work good. 

When I change n_predict then I see error. 

Any solution is to delete model and add again and do nothing in settings.

---

BTW. A see something strange, (Bug?) when I want change Template, click to scroll down list: "custom" and nothing happens. 
I must click on left, no to center word "custom", then list show up.

![Screenshot_20241211-224503_1](https://github.com/user-attachments/assets/a864a825-77ef-48e5-ba4d-e1d836d19f4b)

**Comment by stradeleve** [comment]
Yes, I had that issue as well, so I probed further. What I did first was copy the value and change the n_predict, which is by default 400, to 200, which is supposed to be the minimum. Then I chatted, but I received the same message. So, I selected all, pasted the value, and saved it. I chatted again and encountered the same error. This issue is not limited to n_predict. It also applies to the seed. Leaving n_predict unchanged and editing the seed will lead to the same error. I did some research and found out that any changes to n_predict and seed are seen by the app as strings rather than integers.
